import type { Metadata } from "next";
import {
  // Geist,
  Geist_Mono,
  Host_Grotesk,
} from "next/font/google";
import "./globals.css";
import "./anderson.css";
import { cn } from "@/lib/utils";

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          hostGrotesk.variable,
          geistMono.variable,
          hostGrotesk.className,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
